# Generated by Django 2.0.7 on 2018-07-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('rowid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=500)),
                ('long_description', models.CharField(max_length=1500)),
                ('sdg_code', models.CharField(max_length=10)),
            ],
        ),
    ]
