# Generated by Django 2.0.7 on 2018-07-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='long_description',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='record',
            name='short_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
